# Generated by Django 4.2.7 on 2024-01-08 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0, verbose_name='rating of the task')),
                ('date', models.CharField(max_length=1000, verbose_name='date of the task')),
                ('problemsetName', models.CharField(max_length=1000, verbose_name='problem set name')),
                ('contestId', models.IntegerField(verbose_name='contest id')),
                ('index', models.CharField(max_length=10, verbose_name='index of the task')),
            ],
        ),
    ]
