# Generated by Django 4.2.7 on 2024-01-09 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_dailytask_problemsetname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Olympiad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, unique=True, verbose_name='olympiad name')),
                ('link', models.CharField(max_length=1000, verbose_name='olympiad link')),
                ('description', models.TextField(verbose_name='olympiad description')),
            ],
        ),
    ]
