# Generated by Django 4.2.7 on 2024-01-10 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_topic_topicarchive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='link',
            field=models.CharField(max_length=1000, verbose_name='topic link'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=1000, verbose_name='topic name'),
        ),
        migrations.AlterField(
            model_name='topicarchive',
            name='children',
            field=models.ManyToManyField(blank=True, to='app.topic', verbose_name='topic archive children'),
        ),
        migrations.AlterField(
            model_name='topicarchive',
            name='name',
            field=models.CharField(max_length=1000, verbose_name='topic archive name'),
        ),
    ]
