# Generated by Django 4.2.7 on 2024-01-12 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_topic_link_alter_topic_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingChanges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('rating', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('rating', models.IntegerField(blank=True, default=800)),
                ('rating_changes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ratingchanges')),
            ],
        ),
    ]
