# Generated by Django 4.2.7 on 2024-01-12 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_profile_rating_changes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='rating_changes',
        ),
        migrations.AddField(
            model_name='profile',
            name='rating_changes',
            field=models.ManyToManyField(blank=True, to='app.ratingchanges'),
        ),
    ]
