# Generated by Django 4.2.7 on 2024-01-12 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_profile_rating_changes_profile_rating_changes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingchanges',
            name='rating',
            field=models.IntegerField(default=800),
        ),
    ]
