# Generated by Django 4.2.7 on 2024-01-13 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_ratingchanges_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='codeforces_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
