# Generated by Django 4.2.7 on 2024-01-14 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_dailytasksolvers_solvers_delete_solver_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailytasksolvers',
            name='solvers',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='rating_changes',
        ),
        migrations.AddField(
            model_name='profile',
            name='daily_solver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.dailytasksolvers'),
        ),
        migrations.AddField(
            model_name='ratingchanges',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.profile'),
        ),
    ]
