# Generated by Django 4.2.7 on 2024-01-14 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_dailytasksolvers_solvers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailytasksolvers',
            name='task_name',
        ),
        migrations.AddField(
            model_name='dailytasksolvers',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.dailytask'),
        ),
    ]
