# Generated by Django 4.2.7 on 2024-01-14 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_dailytasksolvers_task_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytasksolvers',
            name='date',
            field=models.DateField(max_length=100, null=True),
        ),
    ]
