# Generated by Django 4.2.7 on 2024-01-14 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_dailytasksolvers_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailytasksolvers',
            name='date',
        ),
    ]
