# Generated by Django 4.2.7 on 2024-01-14 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_remove_dailytasksolvers_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTaskChecking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_date', models.CharField(max_length=100)),
            ],
        ),
    ]
