# Generated by Django 4.2.7 on 2024-06-03 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_task_fight'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='port',
            field=models.IntegerField(default=0),
        ),
    ]
